"""Per-scene illustration loader for Black Spire.

The illustration layer is data-driven off a per-scene image manifest
(``assets/images/manifest.json``), keyed by *scene id* -> image filename under
``assets/images/``.  Every scene has an entry; for now each entry points at one
of the flat placeholder drawings generated by ``tools/generate_assets.py``
(farm, errand, return, road, death, castle).  Node 8 owns the real art set and
will replace these files and their manifest entries without touching the engine
or the story data.

The renderer loads art by scene id via ``Illustrations.load_scene``; the
manifest is the single source of truth for which image a scene shows.
"""

import json
import os

import pygame


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGE_DIR = os.path.join(ROOT, "assets", "images")
MANIFEST_PATH = os.path.join(IMAGE_DIR, "manifest.json")

ILLUSTRATION_SIZE = (512, 512)


def image_path(filename):
    """Absolute path for an image *filename* (as stored in the manifest)."""
    return os.path.join(IMAGE_DIR, filename)


def load_manifest(path=MANIFEST_PATH):
    """Return the per-scene image manifest as ``{scene_id: filename}``."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data["scenes"]


def validate_image_manifest(scenes, path=MANIFEST_PATH):
    """Return a list of problems linking ``scenes`` to the manifest and disk.

    An empty list means every scene references an image slot in the manifest,
    every slot resolves to an on-disk PNG, and the manifest has no dangling
    (orphan) scene ids.
    """
    problems = []
    if not os.path.exists(path):
        problems.append("image manifest missing: %s" % path)
        return problems
    try:
        manifest = load_manifest(path)
    except (OSError, ValueError, KeyError) as exc:
        problems.append("image manifest unreadable (%s): %s" % (path, exc))
        return problems

    scene_ids = set(scenes)
    manifest_ids = set(manifest)
    for sid in sorted(scene_ids - manifest_ids):
        problems.append("%s has no image slot in the manifest" % sid)
    for sid in sorted(manifest_ids - scene_ids):
        problems.append("manifest references unknown scene %r" % sid)
    for sid in sorted(scene_ids.intersection(manifest_ids)):
        filename = manifest[sid]
        if not isinstance(filename, str) or not filename:
            problems.append("%s has an empty image slot" % sid)
            continue
        if not filename.endswith(".png"):
            problems.append("%s slot %r is not a .png" % (sid, filename))
        elif not os.path.exists(image_path(filename)):
            problems.append("%s -> %r missing on disk" % (sid, filename))
    return problems


class Illustrations:
    """Loads and caches illustrations by *scene id*, per the image manifest."""

    def __init__(self, image_dir=IMAGE_DIR, manifest_path=MANIFEST_PATH):
        self.image_dir = image_dir
        self.manifest_path = manifest_path
        self.manifest = load_manifest(manifest_path)
        self._surfaces = {}

    def _load_file(self, filename):
        path = os.path.join(self.image_dir, filename)
        if not os.path.exists(path):
            raise FileNotFoundError("missing illustration %s" % path)
        surf = pygame.image.load(path)
        # ``convert()`` needs a live display surface; stay headless-safe so the
        # loader works in CI and in a windowed run alike.
        if pygame.display.get_surface() is not None:
            surf = surf.convert()
        return surf

    def filename_for(self, scene_id):
        """The image filename the manifest assigns to ``scene_id``."""
        return self.manifest[scene_id]

    def load_scene(self, scene_id):
        """Load (and cache) the illustration for ``scene_id`` via the manifest."""
        if scene_id in self._surfaces:
            return self._surfaces[scene_id]
        filename = self.manifest[scene_id]
        surf = self._load_file(filename)
        self._surfaces[scene_id] = surf
        return surf

    def get_scene(self, scene_id):
        return self.load_scene(scene_id)
